import html
import os
from datetime import datetime


def generate_html_report(target, findings, critical, high, medium, low, risk):

    os.makedirs("reports", exist_ok=True)

    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

    filename = f"reports/report_{timestamp}.html"

    severity_counts = {
        "Critical": critical,
        "High": high,
        "Medium": medium,
        "Low": low
    }

    findings_html = ""

    if findings:

        for finding in findings:

            severity = html.escape(
                str(finding.get("severity", "Unknown"))
            )

            vulnerability = html.escape(
                str(finding.get("type", "Unknown"))
            )

            url = html.escape(
                str(finding.get("url", target))
            )

            parameter = html.escape(
                str(finding.get("parameter", "N/A"))
            )

            evidence = html.escape(
                str(finding.get("evidence", "N/A"))
            )

            recommendation = html.escape(
                str(finding.get("recommendation", "N/A"))
            )

            findings_html += f"""
            <div class="finding">
                <h3>{vulnerability}</h3>

                <p>
                    <strong>Severity:</strong>
                    <span class="severity">{severity}</span>
                </p>

                <p>
                    <strong>URL:</strong> {url}
                </p>

                <p>
                    <strong>Parameter:</strong> {parameter}
                </p>

                <p>
                    <strong>Evidence:</strong> {evidence}
                </p>

                <p>
                    <strong>Recommendation:</strong>
                    {recommendation}
                </p>
            </div>
            """

    else:

        findings_html = """
        <div class="success">
            No potential vulnerabilities were detected.
        </div>
        """

    html_content = f"""
<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="UTF-8">

<meta name="viewport"
      content="width=device-width, initial-scale=1.0">

<title>WebSentinel Security Report</title>

<style>

body {{
    font-family: Arial, sans-serif;
    margin: 40px;
    background: #f4f6f8;
    color: #222;
}}

.container {{
    max-width: 1100px;
    margin: auto;
}}

.header {{
    background: #1f2937;
    color: white;
    padding: 25px;
    border-radius: 10px;
}}

.summary {{
    display: grid;
    grid-template-columns:
        repeat(auto-fit, minmax(160px, 1fr));
    gap: 15px;
    margin-top: 20px;
}}

.card {{
    background: white;
    padding: 20px;
    border-radius: 10px;
    box-shadow:
        0 2px 8px rgba(0, 0, 0, 0.08);
}}

.card h2 {{
    margin: 0;
    font-size: 30px;
}}

.finding {{
    background: white;
    margin-top: 20px;
    padding: 20px;
    border-radius: 10px;
    border-left: 5px solid #555;
    box-shadow:
        0 2px 8px rgba(0, 0, 0, 0.08);
}}

.severity {{
    font-weight: bold;
}}

.success {{
    background: white;
    padding: 20px;
    margin-top: 20px;
    border-radius: 10px;
}}

.footer {{
    margin-top: 40px;
    color: #666;
    font-size: 13px;
}}

</style>

</head>

<body>

<div class="container">

<div class="header">

<h1>WebSentinel Security Report</h1>

<p>
Authorized Security Assessment
</p>

<p>
<strong>Target:</strong>
{html.escape(target)}
</p>

<p>
<strong>Scan Time:</strong>
{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
</p>

<p>
<strong>Overall Risk:</strong>
{html.escape(risk)}
</p>

</div>


<div class="summary">

<div class="card">
<h2>{len(findings)}</h2>
<p>Total Findings</p>
</div>

<div class="card">
<h2>{critical}</h2>
<p>Critical</p>
</div>

<div class="card">
<h2>{high}</h2>
<p>High</p>
</div>

<div class="card">
<h2>{medium}</h2>
<p>Medium</p>
</div>

<div class="card">
<h2>{low}</h2>
<p>Low</p>
</div>

</div>


<h2>Vulnerability Findings</h2>

{findings_html}


<div class="footer">

<p>
Generated by WebSentinel —
Python Web Security Scanner
</p>

<p>
Use only against systems for which you have
explicit authorization.
</p>

</div>

</div>

</body>

</html>
"""

    with open(
        filename,
        "w",
        encoding="utf-8"
    ) as file:

        file.write(html_content)

    return filename
